[settings]
# Number of k-Nearest-Neighbors
k_kNN = 3

# Random seed
random_seed = 41

# Number of iterations for greedy selection
num_iter = 100
mutation_rate = 0.1

# Number of generations for evolutionary selection
num_gen = 50
population_size = 100
num_parents = 20

# Debug flag
debug = False