[settings]
# Serial port settings
host = False
port = /dev/cu.usbmodem58C60539331
baudrate = 921600

base_flash_addr = 0x00201000
num_per_line = 28

binary_name = incr_learn

[paths]
# Directory paths
datasets_dir_path = datasets/
log_dir_path = log/
results_dir_path = results/
artifacts_dir_path = artifacts/
build_dir_path = build/
plots_dir_path = plots/
