[settings]
N_RAM_BUFFER = 200
N_EEPROM_BUFFER = 400

# Random seed
random_seed = 41

# Number of iterations for greedy selection
num_iter = 100

# Number of generations for evolutionary selection
num_gen = 50

# Debug flag
debug = False