[settings]
# Serial port settings
host = True
port_1 = /dev/cu.usbmodem58C60539331
port_2 = /dev/cu.usbmodem58C60536281
baudrate = 921600

base_flash_addr = 0x00201000
bitshift = 10
num_per_line = 28

binary_name = incr_learn

[paths]
# Directory paths
datasets_dir_path = datasets/
log_dir_path = log/
results_dir_path = results/
artifacts_dir_path = artifacts/
build_dir_path = build/
plots_dir_path = plots/

# File names
file_index = file_index.csv
hyperparam_index_file_name = hyper_index.csv
